app {
  kafka {
    bootstrap-servers = "172.25.190.6:9092"
    topic = "app-logs"
    group-id = "log-analytics-group-3"
  }
  database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5432/logs_db"
    user = "admin"
    password = "secret"
  }
  server {
    host = "0.0.0.0"
    port = 8081
  }
  pipeline {
    window-seconds = 30
    error-threshold = 2
    warn-threshold = 5
  }
}
